### ISSUE TITLE
Does not work on iOS.

### ISSUE THREAD

**Issue by kjundev** [jesulink2514/XF-GradientButton#1]
Does not work on iOS.
![](https://github.com/kjundev/KeiSoft/blob/master/error.PNG?raw=true)

**Comment by jesulink2514** [comment]
<img width="1920" alt="2019-08-02_21-00-54" src="https://user-images.githubusercontent.com/2278766/62405934-73c51480-b569-11e9-8c7c-f5addce3490d.png">
